server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE   #lb:表示使用gateway负载均衡工具
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由
            #- After=2021-02-01T20:08:03.291+08:00[Asia/Shanghai]  #在这个时间节点之后网站才能访问
            #- Cookie=username,atguigu   #访问带cookie信息并且username值是atguigu,可用于登录验证

        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb:http://CLOUD-PAYMENT-SERVICE  #http 可以省略不写
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:7001/eureka
