server:
  port: 80

spring:
  application:
    name: cloud-provider-hystrix-payment-service

eureka:
  client:
    register-with-eureka: true    #将自己作为客户端注册到eureka 上
    fetch-registry: true   #获取eureka上服务列表
    service-url:
      defaultZone: http://localhost:7001/eureka/
feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。
